### ISSUE TITLE
Car never stop after moving

### ISSUE THREAD

**Issue by dongvanhung** [unity-car-tutorials/SimpleRaycastVehicle-Unity#1]
When move the car, car will never stop. Its keep moving forever that never stop.

**Comment by unity-car-tutorials** [comment]
As with the

**Comment by unity-car-tutorials** [comment]
As with the Gotow Car Tutorial projects, one can use a simple hack using the drag coefficient.

For example, in the 2nd example, this can be achieved by adding the following code to FixedUpdate()

` rb.drag = rb.velocity.magnitude / 10;`
